
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nestdb
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306

  # phpmyadmin:
  #   image: phpmyadmin:5.2.2
  #   ports:
  #     - 3110:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: example
  #   depends_on:
  #     - db
  #   volumes:
  #     - phpmyadmin:/sessions

volumes:
  data:
  # phpmyadmin:
